[package]
name = "middlesox-cli"
version.workspace = true
edition = "2021"
description = "CLI for interacting with Middlesox backends"

[[bin]]
name = "msx"
path = "src/main.rs"

[dependencies]
middlesox.workspace = true
middlesox-socket.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
dirs.workspace = true
