[package]
name = "middlesox-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Middlesox daemon - event-driven window manager controller"

[[bin]]
name = "middlesoxd"
path = "src/main.rs"

[dependencies]
middlesox.workspace = true
middlesox-socket.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs.workspace = true
